name: Scrape Talk Locations

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  actions: write     # required if you want your push to trigger other workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install deps
        run: |
          pip install -U jupyter pandas requests beautifulsoup4 geopy getorg

      - name: Run notebook
        run: |
          jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

      - name: Commit & push (if any)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}   # MUST include workflow scope
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Automated update of talk locations"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/Gee1225/gee1225.github.io.git
          git push origin HEAD
